#!/usr/bin/env bash

prod_filepath="$1"
prod_filename=`basename $prod_filepath`

path=`dirname $prod_filepath`

filename="${prod_filename%%.*}"
extension=".${prod_filename#*.}"
if [ "$prod_filename" != "$filename$extension" ]; then
  extension=''
fi

spec_filename="${filename}_spec${extension}"

mkdir -p $path
mkdir -p spec/$path
touch $path/$prod_filename
touch spec/$path/$spec_filename
